# Configurações HTTP da API
quarkus.http.port=8080
quarkus.http.cors=true

# Ativação do Micrometer + Prometheus
quarkus.micrometer.enabled=true
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/q/metrics

# Coleta automática de métricas do Servidor HTTP e da JVM
quarkus.micrometer.binder.http-server.enabled=true
quarkus.micrometer.binder.jvm=true

# Simulação de conexão com o banco PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=sua_senha
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/seu_banco